<script lang="ts">
	import { adminStore as store } from '$lib/admin/store.svelte';
	import type { FinancialDocument, FinancialTask, ProjectPayment } from '$lib/admin/types';
	let { tasks, payments, documents, onopenproject }: { tasks: FinancialTask[]; payments: ProjectPayment[]; documents: FinancialDocument[]; onopenproject: (id: string) => void } = $props();
	const money = (value: number) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(value);
	const rows = $derived(store.projects.map((project) => ({ project, tasks: tasks.filter((task) => task.projectId === project.id), payments: payments.filter((payment) => payment.projectId === project.id), documents: documents.filter((document) => document.projectId === project.id) })).filter((row) => row.tasks.length || row.payments.length || row.documents.length));
</script>

<header class="heading"><div><p>ACCOUNTING</p><h1>Financials</h1><span>Current project values and historical invoice documents.</span></div></header>
{#if rows.length}<div class="list">{#each rows as row (row.project.id)}<article><div><h2>{row.project.name}</h2><span>{row.project.projectNumber}</span></div><div class="totals"><span>Total Project Invoice<strong>{money(row.tasks.reduce((sum, task) => sum + task.taskTotal, 0))}</strong></span><span>Amount Paid to Date<strong>{money(row.payments.reduce((sum, payment) => sum + payment.amount, 0))}</strong></span><span>Amount Due<strong>{money(row.tasks.reduce((sum, task) => sum + task.billedAmount, 0))}</strong></span></div><footer><span>{row.documents.length} invoice document{row.documents.length === 1 ? '' : 's'}</span><button onclick={() => onopenproject(row.project.id)}>Open Project Financials</button></footer></article>{/each}</div>{:else}<div class="empty"><h2>No financial records yet</h2><p>Add financial tasks from a project.</p></div>{/if}

<style>
	.heading { margin-bottom: 28px; } .heading p { margin: 0 0 8px; color: #718667; font-size: 10px; font-weight: 800; letter-spacing: .15em; } .heading h1 { margin: 0 0 7px; color: #1b2a44; font: 600 35px/1.1 Georgia, serif; } .heading span { color: #747e86; font-size: 14px; }
	.list { display: grid; gap: 12px; max-width: 980px; } article { border: 1px solid #dfe4df; border-radius: 12px; background: white; padding: 18px; } article h2 { margin: 0 0 4px; color: #25344b; font-size: 17px; } article > div > span, footer > span { color: #747e86; font-size: 12px; } .totals { display: grid; grid-template-columns: repeat(3, 1fr); gap: 10px; margin: 16px 0; } .totals span { display: grid; gap: 5px; border-radius: 8px; background: #f5f7f4; padding: 12px; color: #7a858d; font-size: 10px; font-weight: 700; text-transform: uppercase; } .totals strong { color: #26384d; font-size: 17px; } footer { display: flex; align-items: center; justify-content: space-between; gap: 12px; border-top: 1px solid #e1e6e1; padding-top: 12px; } button { border: 1px solid #cfd6d1; border-radius: 7px; background: white; padding: 8px 12px; color: #203552; font: inherit; font-size: 12px; font-weight: 700; cursor: pointer; } .empty { border: 1px solid #dfe4df; border-radius: 12px; background: white; padding: 48px; text-align: center; } .empty h2 { color: #25344b; } .empty p { color: #747e86; } @media(max-width: 650px) { .totals { grid-template-columns: 1fr; } footer { align-items: stretch; flex-direction: column; } }
</style>
