import type { ActionItem, AppUser, CalendarEvent, Client, DocumentItem, Estimate, Expense, Invoice, MailThread, Project, Task, Vendor } from './types';

export const clients: Client[] = [
 { id:'c1', name:'Harbor Ridge Holdings', type:'Company', email:'claire@harborridge.example', phone:'(910) 555-0142', address:'1820 Eastwood Rd, Wilmington, NC', notes:'Residential community feasibility inquiry. Interested in moving quickly.', projectIds:[], contacts:[{id:'ct1',name:'Claire Bennett',role:'Managing Partner',email:'claire@harborridge.example',phone:'(910) 555-0142',preferred:'Email',primary:true}] },
 { id:'c2', name:'Cape Fear Communities', type:'Company', email:'morgan@capefear.example', phone:'(910) 555-0188', address:'704 Water Street, Wilmington, NC', notes:'Long-term client. Weekly permitting updates preferred.', projectIds:['p1','p2'], contacts:[{id:'ct2',name:'Morgan Ellis',role:'Development Director',email:'morgan@capefear.example',phone:'(910) 555-0188',preferred:'Phone',primary:true},{id:'ct3',name:'Sam Rivera',role:'Project Manager',email:'sam@capefear.example',phone:'(910) 555-0119',preferred:'Email'}] },
 { id:'c3', name:'Seabrook Commercial Partners', type:'Company', email:'daniel@seabrook.example', phone:'(910) 555-0167', address:'88 Market Plaza, Southport, NC', notes:'Completed retail site. Keep closeout records available.', projectIds:['p3'], contacts:[{id:'ct4',name:'Daniel Cho',role:'Principal',email:'daniel@seabrook.example',phone:'(910) 555-0167',preferred:'Email',primary:true},{id:'ct5',name:'Renee Walsh',role:'Controller',email:'renee@seabrook.example',phone:'(910) 555-0194',preferred:'Email'}] }
];
export const projects: Project[] = [
 {id:'p1',name:'Pine Haven Subdivision',clientId:'c2',address:'Castle Hayne, NC · PIN 3221-48-9912',status:'Active',phase:'Permitting',summary:'42-lot residential subdivision moving through county technical review.',waitingOn:'New Hanover County engineering review',nextMilestone:'Site Plan Approval',lastActivity:'Today, 9:42 AM',budget:148000,invoiced:89500,costs:32740},
 {id:'p2',name:'Riverbend Pump Station',clientId:'c2',address:'Leland, NC',status:'Pending',phase:'Engineering / Design',summary:'Pump station capacity assessment and preliminary engineering.',waitingOn:'Survey boundary confirmation',nextMilestone:'30% Design Review',lastActivity:'Aug 18',budget:64000,invoiced:22000,costs:9400},
 {id:'p3',name:'Seabrook Market Center',clientId:'c3',address:'Southport, NC',status:'Completed',phase:'Closeout',summary:'Commercial retail site entitlement, stormwater design, and construction coordination.',nextMilestone:'Complete',lastActivity:'Jul 29',budget:212000,invoiced:212000,costs:74820}
];
export const actions: ActionItem[] = [
 {id:'a1',title:'County reviewer requested revised drainage notes',detail:'Response received on Pine Haven permit package. Review comments and assign revisions.',state:'Needs Action',priority:'High',due:'Today',age:'18 min ago',projectId:'p1',clientId:'c2',source:'Permitting inbox'},
 {id:'a2',title:'New project inquiry from Claire Bennett',detail:'Residential development feasibility for approximately 18 acres near Wilmington.',state:'New',priority:'High',due:'Today',age:'2 hrs ago',clientId:'c1',source:'Website inquiry'},
 {id:'a3',title:'Follow up with county reviewer',detail:'No response since permit resubmittal 7 days ago.',state:'Waiting',priority:'High',due:'Overdue · Aug 20',age:'7 days waiting',projectId:'p1',clientId:'c2',source:'Follow-up'},
 {id:'a4',title:'Invoice DLD-1048 is due tomorrow',detail:'Balance of $12,500 for Pine Haven Subdivision.',state:'Needs Action',priority:'Medium',due:'Tomorrow',age:'Issued Aug 8',projectId:'p1',clientId:'c2',source:'Accounting'},
 {id:'a5',title:'Prepare 30% design review packet',detail:'Confirm survey updates are incorporated before review.',state:'Needs Action',priority:'Medium',due:'Aug 25',age:'3 days ago',projectId:'p2',clientId:'c2',source:'Task'},
 {id:'a6',title:'Site inspection at Pine Haven',detail:'Stormwater inspection with contractor and county representative.',state:'New',priority:'Low',due:'Aug 26 · 9:00 AM',age:'Calendar',projectId:'p1',clientId:'c2',source:'Calendar'}
];
export const tasks: Task[] = [{id:'t1',title:'Revise drainage calculation narrative',projectId:'p1',clientId:'c2',due:'Aug 22',priority:'High',status:'In progress',assignee:'Branch Williams'},{id:'t2',title:'Confirm survey boundary with Coastal Surveying',projectId:'p2',clientId:'c2',due:'Aug 23',priority:'High',status:'Waiting',assignee:'Branch Williams'},{id:'t3',title:'Archive final as-builts',projectId:'p3',clientId:'c3',due:'Jul 29',priority:'Low',status:'Done',assignee:'Office'}];
export const mail: MailThread[] = [
 {id:'m1',mailbox:'Permitting',sender:'Avery Collins',email:'avery.collins@nhcgov.example',subject:'Pine Haven — Review comments',preview:'We completed our second review. Please address the drainage narrative items…',time:'9:42 AM',unread:true,projectId:'p1',clientId:'c2',messages:[{from:'Avery Collins',body:'We completed our second review. Please address the drainage narrative items highlighted in the attached comment letter. Once received, we can route the package for final sign-off.',time:'Today, 9:42 AM'}]},
 {id:'m2',mailbox:'Branch',sender:'Morgan Ellis',email:'morgan@capefear.example',subject:'Re: Pine Haven timing',preview:'Thanks for the update. Is late September still realistic for approval?',time:'8:16 AM',unread:true,projectId:'p1',clientId:'c2',messages:[{from:'Morgan Ellis',body:'Thanks for the update. Is late September still realistic for approval? We are coordinating the closing schedule.',time:'Today, 8:16 AM'}]},
 {id:'m3',mailbox:'Office',sender:'Claire Bennett',email:'claire@harborridge.example',subject:'18-acre residential property',preview:'I submitted the website form and wanted to include the parcel sketch…',time:'Yesterday',unread:true,clientId:'c1',messages:[{from:'Claire Bennett',body:'I submitted the website form and wanted to include the parcel sketch. We would appreciate a call about feasibility and next steps.',time:'Yesterday, 4:31 PM'}]},
 {id:'m4',mailbox:'Accounting',sender:'Renee Walsh',email:'renee@seabrook.example',subject:'Final payment confirmation',preview:'Our records show the final payment cleared. Thank you for your help.',time:'Aug 19',unread:false,projectId:'p3',clientId:'c3',messages:[{from:'Renee Walsh',body:'Our records show the final payment cleared. Thank you for your help throughout the project.',time:'Aug 19, 11:05 AM'}]}
];
export const documents: DocumentItem[] = [{id:'d1',name:'Pine_Haven_Review_Comments_02.pdf',category:'Permits',projectId:'p1',clientId:'c2',size:'1.8 MB',updated:'Today',shared:false},{id:'d2',name:'Pine_Haven_Site_Plan_60pct.pdf',category:'Plans',projectId:'p1',clientId:'c2',size:'8.4 MB',updated:'Aug 18',shared:true},{id:'d3',name:'Riverbend_Boundary_Survey.pdf',category:'Surveys',projectId:'p2',clientId:'c2',size:'3.2 MB',updated:'Aug 14',shared:false},{id:'d4',name:'Seabrook_Final_AsBuilts.pdf',category:'Engineering',projectId:'p3',clientId:'c3',size:'12.1 MB',updated:'Jul 28',shared:true}];
export const events: CalendarEvent[] = [{id:'e1',title:'Pine Haven site inspection',date:'Aug 26',time:'9:00 AM',type:'Inspection',projectId:'p1',clientId:'c2',shared:true},{id:'e2',title:'Call Claire — new inquiry',date:'Aug 21',time:'2:30 PM',type:'Appointment',clientId:'c1',shared:false},{id:'e3',title:'Technical review follow-up',date:'Aug 22',time:'10:00 AM',type:'Reminder',projectId:'p1',clientId:'c2',shared:false},{id:'e4',title:'Riverbend 30% design review',date:'Aug 28',time:'1:00 PM',type:'Meeting',projectId:'p2',clientId:'c2',shared:true}];
export const vendors: Vendor[] = [{id:'v1',name:'Coastal Surveying Group',category:'Surveying',contact:'Jamie Price',email:'jamie@coastalsurvey.example',phone:'(910) 555-0121',spend:18450,projectIds:['p1','p2']},{id:'v2',name:'Tidewater Environmental',category:'Environmental Consulting',contact:'Alexis Grant',email:'alexis@tidewater.example',phone:'(910) 555-0133',spend:12600,projectIds:['p1']},{id:'v3',name:'Cape Utility Contractors',category:'Construction',contact:'Drew Mason',email:'drew@capeutility.example',phone:'(910) 555-0177',spend:53770,projectIds:['p3']}];
export const estimates: Estimate[] = [{id:'EST-2026-031',clientId:'c1',title:'Harbor Ridge feasibility & due diligence',amount:18500,status:'Draft',date:'Aug 20'},{id:'EST-2026-024',clientId:'c2',title:'Pine Haven engineering & permitting',amount:148000,status:'Accepted',date:'May 4'}];
export const invoices: Invoice[] = [{id:'DLD-1048',clientId:'c2',projectId:'p1',amount:12500,status:'Due',due:'Aug 22',paid:0},{id:'DLD-1041',clientId:'c2',projectId:'p1',amount:24000,status:'Paid',due:'Jul 30',paid:24000},{id:'DLD-1027',clientId:'c3',projectId:'p3',amount:28600,status:'Paid',due:'Jul 15',paid:28600}];
export const expenses: Expense[] = [{id:'x1',vendorId:'v1',projectId:'p1',description:'Supplemental topographic survey',amount:4200,date:'Aug 15',category:'Project cost'},{id:'x2',vendorId:'v2',projectId:'p1',description:'Wetland flag verification',amount:1850,date:'Aug 6',category:'Project cost'},{id:'x3',vendorId:'v3',projectId:'p3',description:'Utility closeout coordination',amount:8700,date:'Jul 18',category:'Project cost'}];
export const users: AppUser[] = [{id:'u1',name:'Branch Williams',email:'branch@dogwoodlanddev.com',role:'Super User',status:'Active',overrides:{}},{id:'u2',name:'Office Administrator',email:'office@dogwoodlanddev.com',role:'Admin',status:'Active',overrides:{Accounting:false}},{id:'u3',name:'Accounting',email:'accounting@dogwoodlanddev.com',role:'Accounting',status:'Active',overrides:{}},{id:'u4',name:'Field Coordinator',email:'field@dogwoodlanddev.com',role:'User',status:'Invited',overrides:{Projects:true,Documents:true}}];
